# Create new tag
# git tag v0.0.1
# git push --tags

name: Release on publish

on:
  release:
    types: [published]

env:
  DOTNET_VERSION: '7.0.x'

jobs:
  release:
    name: Release
    
    strategy:
      matrix:
        kind: ['linux', 'windows']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="lifelogbb-$tag-${{ matrix.target }}"

          # Build everything
          dotnet publish --framework net7.0 --runtime "${{ matrix.target }}" -c Release -o "$release_name"
    
          # Build migration bundle https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            dotnet ef migrations bundle --output "./${release_name}/efbundle.exe"
          else
            dotnet ef migrations bundle --self-contained -r linux-x64 --output "./${release_name}/efbundle"
          fi
          

          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
            tar czvf "${release_name}.tar.gz" "$release_name"
          fi

          # Delete output directory
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "lifelogbb*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Reference: https://www.newline.co/@krishna/release-management-with-aspnet-core-and-github-actions--ff31a146
